### ISSUE TITLE
Ошибка при установке: отсутствие lib/SDK/vendor/autoload.php

### ISSUE THREAD

**Issue by lyubsky** [mindbox-moscow/bitrix#1]
Fatal error: require(): Failed opening required '[докрут]www/bitrix/modules/mindbox/lib/SDK/vendor/autoload.php' (include_path='.:/usr/share/php') in [докрут]www/bitrix/modules/mindbox/include.php on line 5

**Comment by itsyrulnikov** [comment]
SDK находится в отдельном репозитории https://github.com/mindbox-moscow/php-sdk
