### ISSUE TITLE
Правила работы с корзиной - действие Применить скидку из HighLoad блока Mindbox

### ISSUE THREAD

**Issue by azverin-sb** [mindbox-moscow/bitrix#47]
В правилах нет возможности указать действие Применить скидку из HighLoad блока Mindbox

**Comment by MaximBurcev** [comment]
Добрый день. Какая версия модуля у вас установлена?
Какая версия ядра 1С-Битрикс?

**Comment by MaximBurcev** [comment]
Установите, пожалуйста, последнюю версию модуля. В ней уже реализованы обработчики, которые позволяют реализовать правила работы с корзиной через хайлоадблок.

**Comment by azverin-sb** [comment]
Последняя версия модуля падает при создании заказа 
[Error] 
Call to undefined method Bitrix\Sale\Order::getParameter() (0)
/var/www/_default/www/bitrix/modules/mindbox.marketing/lib/Event.php:637
#0: Mindbox\Event::OnSaleOrderBeforeSavedHandler(object, array)
	
#1: call_user_func_array(array, array)
	/var/www/_default/www/bitrix/modules/main/lib/eventmanager.php:435
#2: Bitrix\Main\EventManager->sendToEventHandler(array, object)
	/var/www/_default/www/bitrix/modules/main/lib/eventmanager.php:371
#3: Bitrix\Main\EventManager->send(object)
	/var/www/_default/www/bitrix/modules/main/lib/event.php:142
#4: Bitrix\Main\Event->send()
	/var/www/_default/www/bitrix/modules/sale/lib/orderbase.php:1397
#5: Bitrix\Sale\OrderBase->callEventOnBeforeOrderSaved()
	/var/www/_default/www/bitrix/modules/sale/lib/orderbase.php:1068
#6: Bitrix\Sale\OrderBase->save()
	/var/www/_default/www/bitrix/modules/sale/lib/order.php:2325
#7: Bitrix\Sale\Order->save()
	/var/www/_default/www/bitrix/components/bitrix/sale.order.ajax/class.php:6282
#8: SaleOrderAjax->saveOrder(boolean)
	/var/www/_default/www/bitrix/components/bitrix/sale.order.ajax/class.php:4705
#9: SaleOrderAjax->saveOrderAjaxAction()
	/var/www/_default/www/bitrix/components/bitrix/sale.order.ajax/class.php:6093
#10: SaleOrderAjax->doAction(string)
	/var/www/_default/www/bitrix/components/bitrix/sale.order.ajax/class.php:6351
#11: SaleOrderAjax->executeComponent()
	/var/www/_default/www/bitrix/modules/main/classes/general/component.php:656
#12: CBitrixComponent->includeComponent(string, array, NULL, boolean)
	/var/www/_default/www/bitrix/modules/main/classes/general/main.php:1071
#13: CAllMain->IncludeComponent(string, string, array)
	/var/www/_default/www/bitrix/components/bitrix/sale.order.ajax/ajax.php:45

В правилах по прежнему нет возможности указать действие Применить скидку из HighLoad блока Mindbox

**Comment by MaximBurcev** [comment]
Удалите, пожалуйста, модуль полностью, включая записи в бд. Также необходимо удалить все записи с модулем в таблице b_module_to_module. После этого необходимо заново установить модуль.

**Comment by azverin-sb** [comment]
Правила расчета появились

1 после удаления таблиц теряются все mindboxID пользователей, это влияет на оформления заказа, возникает ошибка из-за того что
```
if (!(\Mindbox\Helper::isUnAuthorizedOrder($arUser) || (is_object($USER) && !$USER->IsAuthorized()))) {
            $customer->setId('mindboxId', $mindboxId);
```
ставит False, в момент оформления заказа возникает ошибка "False" не является корректным целым числом. Поле должно содержать целое число не превышающее 2147483647.

**Comment by azverin-sb** [comment]
Кроме того модуль не дает проставлять пользователям mindboxID, блокируется сохранение юзера.

Если проставить в БД mindboxID для пользователя, то при оформлении возникает другая ошибка: JSON error: Malformed UTF-8 characters, possibly incorrectly encoded [5] (100)
